layout_spectrum: 0.174032
typography_spectrum: 0.01603763
color:
  saturation: 0.009500364
  lightness: 0.1036831
  brandStrength: 0.08494456
  rhythmicContrast: 0.7794253
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
name: Kevin Canavan2
